<?php
    return
        array(
            'urlFormat'=>'path',
            'showScriptName'=>false,
            'caseSensitive'=>false,
            'useStrictParsing'=>true,
            'urlSuffix'=>'/',
            'rules'=>array(
                '<_m:(hqcmf|gii)>'=>'<_m>',
                '<_m:(hqcmf|gii)>/<controller:\w+>'=>'<_m>/<controller>',
                '<_m:(hqcmf|gii)>/<controller:\w+>/<action:\w+>'=>'<_m>/<controller>/<action>',
                ''=>'site/index',
                '<_c:\w+>'=>'<_c>/index',
                '<_c:\w+>/<_a:\w+>'=>'<_c>/<_a>',
            )
        );
?>