-- MySQL Script generated by MySQL Workbench
-- Вт 08 апр 2014 22:57:52
-- Model: New Model    Version: 1.0

-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user` ;

CREATE TABLE IF NOT EXISTS `user` (
  `u_id` MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `u_login` VARCHAR(24) NOT NULL,
  `u_pass` VARCHAR(40) NOT NULL,
  `u_mail` VARCHAR(54) NULL,
  `u_switch` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`u_id`),
  UNIQUE INDEX `u_id_UNIQUE` (`u_id` ASC),
  UNIQUE INDEX `u_login_UNIQUE` (`u_login` ASC),
  UNIQUE INDEX `u_mail_UNIQUE` (`u_mail` ASC),
  INDEX `u_pass` (`u_pass` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user_role` ;

CREATE TABLE IF NOT EXISTS `user_role` (
  `ur_id` MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ur_name` VARCHAR(255) NOT NULL,
  `ur_caption` VARCHAR(255) NOT NULL,
  `ur_switch` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`ur_id`),
  UNIQUE INDEX `ur_name_UNIQUE` (`ur_name` ASC),
  UNIQUE INDEX `ur_caption_UNIQUE` (`ur_caption` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user_role_relation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user_role_relation` ;

CREATE TABLE IF NOT EXISTS `user_role_relation` (
  `urr_id` MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `urr_u_id` MEDIUMINT UNSIGNED NOT NULL,
  `urr_ur_id` MEDIUMINT UNSIGNED NOT NULL,
  PRIMARY KEY (`urr_id`),
  INDEX `fk_urr_u_idx` (`urr_u_id` ASC),
  INDEX `fk_urr_ur_idx` (`urr_ur_id` ASC),
  CONSTRAINT `fk_urr_u`
    FOREIGN KEY (`urr_u_id`)
    REFERENCES `user` (`u_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_urr_ur`
    FOREIGN KEY (`urr_ur_id`)
    REFERENCES `user_role` (`ur_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;
